/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: c5328515300cba39d04d621fdbd5ae5c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "Chat";
	}
	interface Env {
		Chat: DurableObjectNamespace<import("./src/server").Chat>;
		AI: Ai;
		TASK_REMINDER_WORKFLOW: Workflow /* TaskReminderWorkflow */;
		BATCH_TASK_REMINDER_WORKFLOW: Workflow /* BatchTaskReminderWorkflow */;
	}
}
interface Env extends Cloudflare.Env {}
